-- MySQL Script generated by MySQL Workbench
-- Sun Sep 30 23:25:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema final_work
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `final_work` ;

-- -----------------------------------------------------
-- Schema final_work
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `final_work` ;
USE `final_work` ;

-- -----------------------------------------------------
-- Table `final_work`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_work`.`User` (
  `id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NOT NULL,
  `organisation` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `str` VARCHAR(8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_work`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_work`.`Warehouse` (
  `id` INT NOT NULL auto_increment,
  `address` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk_Warehouse_User_idx` (`id_user` ASC),
  CONSTRAINT `fk_Warehouse_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `final_work`.`User` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_work`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_work`.`Item` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_Item_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Item_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `final_work`.`User` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_work`.`Transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_work`.`Transfer` (
  `id` INT NOT NULL auto_increment,
  `date` DATETIME NOT NULL,
  `is_foreign` varchar(3) NOT NULL,
  `type` VARCHAR(3) NOT NULL,
  `id_warehouse` INT NOT NULL,
  PRIMARY KEY (`id`, `id_warehouse`),
  INDEX `fk_table1_Warehouse1_idx` (`id_warehouse` ASC),
  CONSTRAINT `fk_table1_Warehouse1`
    FOREIGN KEY (`id_warehouse`)
    REFERENCES `final_work`.`Warehouse` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_work`.`Foreign_transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_work`.`Foreign_transfer` (
  `name` VARCHAR(45) NOT NULL,
  `id_transfer` INT NOT NULL,
  INDEX `fk_Foreign_transfer_Transfer1_idx` (`id_transfer` ASC),
  PRIMARY KEY (`id_transfer`),
  CONSTRAINT `fk_Foreign_transfer_Transfer1`
    FOREIGN KEY (`id_transfer`)
    REFERENCES `final_work`.`Transfer` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_work`.`Batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_work`.`Batch` (
  `id_item` INT NOT NULL,
  `quantity` INT NOT NULL,
  `id_warehouse` INT NOT NULL,
  INDEX `fk_Batch_Item1_idx` (`id_item` ASC),
  PRIMARY KEY (`id_item`, `id_warehouse`),
  INDEX `fk_Batch_Warehouse1_idx` (`id_warehouse` ASC),
  CONSTRAINT `fk_Batch_Item1`
    FOREIGN KEY (`id_item`)
    REFERENCES `final_work`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Batch_Warehouse1`
    FOREIGN KEY (`id_warehouse`)
    REFERENCES `final_work`.`Warehouse` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_work`.`Transfer_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_work`.`Transfer_batch` (
  `Transfer_id` INT NOT NULL,
  `Item_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`Transfer_id`, `Item_id`),
  INDEX `fk_Transfer_batch_Item1_idx` (`Item_id` ASC),
  CONSTRAINT `fk_Transfer_batch_Transfer1`
    FOREIGN KEY (`Transfer_id`)
    REFERENCES `final_work`.`Transfer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transfer_batch_Item1`
    FOREIGN KEY (`Item_id`)
    REFERENCES `final_work`.`Item` (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET SQL_SAFE_UPDATES = 0;
